### ISSUE TITLE
Pre Trained Models

### ISSUE THREAD

**Issue by jerrymatjila** [facebookresearch/Listen-to-Look#1]
Do you have pre trained models?

**Comment by zzzzjw** [comment]
> Do you have pre trained models?

**Comment by rhgao** [comment]
The ImageAudio model for ActivityNet is shared here: https://utexas.box.com/s/8rxijymjo0kx4e9jk7byobdc8vnf377l

The listen to look model can be trained on the pre-computed features using the command provided.
