### ISSUE TITLE
train or val ,pretrained models?

### ISSUE THREAD

**Issue by ctx2333-ctx** [facebookresearch/Listen-to-Look#3]
Dear Doctor:
The features you provided is fussy to distinguish whether it‘train set or val set.I beg for the clearly divided dataset（audio+visual）or features.
What's more ,I can't find the pretrained model.
Thanks！

**Comment by rhgao** [comment]
The split and the ImageAudio model for ActivityNet is shared here: https://utexas.box.com/s/8rxijymjo0kx4e9jk7byobdc8vnf377l

**Comment by ctx2333-ctx** [comment]
> The split and the ImageAudio model for ActivityNet is shared here: https://utexas.box.com/s/8rxijymjo0kx4e9jk7byobdc8vnf377l

get it ,thanks!
